name: NodeJS with Webpack

on:
  push:
    tags:        
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.GITHUB_BASE_REF }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Npm Install    
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: false
    
    - name: Build
      run:  npm run build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        user_name: github-actions[bot]
        user_email: 'github-actions[bot]@users.noreply.github.com'
